### ISSUE TITLE
遇到sonar发送聊天消息会引发一个报错

### ISSUE THREAD

**Issue by LittleNightmare** [Asvel/ffxiv-literal-map-link#1]
```c#
2022-05-09 15:52:16.480 -04:00 [ERR] Could not invoke registered OnMessageDelegate for HandleChatMessage
System.ArgumentOutOfRangeException: Length cannot be less than zero. (Parameter 'length')
   at System.String.Substring(Int32 startIndex, Int32 length)
   at LiteralMapLink.LiteralMapLink.HandleChatMessage(XivChatType type, UInt32 senderId, SeString& sender, SeString& message, Boolean& isHandled)
   at Dalamud.Game.Gui.ChatGui.HandlePrintMessageDetour(IntPtr manager, XivChatType chattype, IntPtr pSenderName, IntPtr pMessage, UInt32 senderid, IntPtr parameter) in D:\Code\FFXIV\__Dalamud__\Dalamud\Dalamud\Game\Gui\ChatGui.cs:line 354

```
应该是sonar的消息，可以考虑兼容下？（或者说插件发到聊天频道的消息都会这样？

**Comment by Asvel** [comment]
看了一下Sonar的实现，它生成的坐标链接的内部结构和游戏自身生成的不一致。
对我这边来说是收到了正常游戏不可能产生的数据，对Sonar来说是虽然结构和原装不一致但是在游戏里工作正常，我太不确定这种情况应该由哪边来改。
不过如果我这边改的话估计也只是catch一下静默掉，和现在没有本质区别只是不污染日志，先不管它吧。

**Comment by KirisameVanilla** [comment]
请问这个工具还在更新吗

**Comment by Asvel** [comment]
维护性更新还在，遇到什么问题了吗，还是又到了卫月升api版本的时节了？

**Comment by LittleNightmare** [comment]
> 维护性更新还在，遇到什么问题了吗，还是又到了卫月升api版本的时节了？

国服7国际服8了（顺便建议try catch一下，比方说crash了看一眼文本有sonar就不管了）

**Comment by Asvel** [comment]
好多新版本哦_(┐「ε:)_，我更新一下。

**Comment by KirisameVanilla** [comment]
> 维护性更新还在，遇到什么问题了吗，还是又到了卫月升api版本的时节了？

您好，您提供的仓库下载的Literal Map Link显示版本过老无法使用2333

**Comment by KirisameVanilla** [comment]
![image](https://user-images.githubusercontent.com/118162831/215235800-133b0abf-89d9-4f59-a7c0-4c6db1b69bd3.png)
如图

**Comment by Asvel** [comment]
更新了，报错也静默掉了。

@V4n1ll4444
